query GetChats {
    chats {
        id
        type
        users {
            id
            email
            username
        }
        messages {
            id
            date
            message

            user {
                id
                email
                username
            }
        }
    }
}
