query GetPrivateChat($contactId: Int!) {
    privateChat(contactId: $contactId) {
        name
        id
        type
        messages {
            id
            date
            message
            user {
                id
            }
        }
    }
}
