version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    container_name: "front"
    tty: true
    depends_on:
      - back
    volumes:
      - ./front/dist:/app/dist
    command: npm run build
  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    command: npm run start:prod
  nginx:
    image: nginx:alpine
    container_name: "nginx"
    links:
      - back:back
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front/dist:/var/www/front
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
