version: '3'
services:
    back:
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: builder
        command: npm run start:back:prod
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        ports: 
          - '5436:5432'
        environment:
            POSTGRES_DB: web-chat
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    nginx:
        build:
            context: ./
            dockerfile: ./Dockerfile
        links:
            - back:back
        depends_on:
            - back
        ports:
            - '${port}:80'
        volumes:
            - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
